# Auth opcodes
CMD_AUTH_LOGON_CHALLENGE = 0x00
CMD_AUTH_LOGON_PROOF     = 0x01
CMD_REALM_LIST           = 0x10

# World opcodes — auth
CMSG_AUTH_SESSION        = 0x1ED
SMSG_AUTH_CHALLENGE      = 0x1EC
SMSG_AUTH_RESPONSE       = 0x1EE

# Character management
CMSG_CHAR_ENUM           = 0x037
SMSG_CHAR_ENUM           = 0x03B
CMSG_CHAR_CREATE         = 0x036
SMSG_CHAR_CREATE         = 0x03A
CMSG_CHAR_DELETE         = 0x038
SMSG_CHAR_DELETE         = 0x03C
CMSG_PLAYER_LOGIN        = 0x03D
SMSG_LOGIN_VERIFY_WORLD  = 0x236

# Login sequence
SMSG_ACCOUNT_DATA_TIMES  = 0x209
SMSG_TUTORIAL_FLAGS      = 0x0FD
SMSG_INITIAL_SPELLS      = 0x12A
SMSG_ACTION_BUTTONS      = 0x129
SMSG_FACTION_LIST        = 0x124
SMSG_LOGIN_SETTIMESPEED  = 0x042
SMSG_UPDATE_OBJECT       = 0x0A9
SMSG_DESTROY_OBJECT      = 0x0AA
SMSG_MOTD                = 0x33D

# Ping
CMSG_PING                = 0x1DC
SMSG_PONG                = 0x1DD

# Chat
CMSG_MESSAGECHAT         = 0x095
SMSG_MESSAGECHAT         = 0x096

# Logout
CMSG_PLAYER_LOGOUT       = 0x04A
CMSG_LOGOUT_REQUEST      = 0x04B
SMSG_LOGOUT_RESPONSE     = 0x04C
SMSG_LOGOUT_COMPLETE     = 0x04D
CMSG_LOGOUT_CANCEL       = 0x04E

# Name/query
CMSG_NAME_QUERY              = 0x050
SMSG_NAME_QUERY_RESPONSE     = 0x051
CMSG_ITEM_QUERY_SINGLE       = 0x056
SMSG_ITEM_QUERY_SINGLE_RESPONSE = 0x058
CMSG_GAMEOBJECT_QUERY        = 0x05E
SMSG_GAMEOBJECT_QUERY_RESPONSE = 0x05F
CMSG_CREATURE_QUERY          = 0x060
SMSG_CREATURE_QUERY_RESPONSE = 0x061

# Movement / teleport
SMSG_NEW_WORLD           = 0x03E
SMSG_TRANSFER_PENDING    = 0x03F
MSG_MOVE_TELEPORT_ACK    = 0x0C7

# Movement opcodes (MSG_ = bidirectional, same opcode CMSG and SMSG)
MSG_MOVE_START_FORWARD       = 0x0B5
MSG_MOVE_START_BACKWARD      = 0x0B6
MSG_MOVE_STOP                = 0x0B7
MSG_MOVE_START_STRAFE_LEFT   = 0x0B8
MSG_MOVE_START_STRAFE_RIGHT  = 0x0B9
MSG_MOVE_STOP_STRAFE         = 0x0BA
MSG_MOVE_JUMP                = 0x0BB
MSG_MOVE_START_TURN_LEFT     = 0x0BC
MSG_MOVE_START_TURN_RIGHT    = 0x0BD
MSG_MOVE_STOP_TURN           = 0x0BE
MSG_MOVE_START_PITCH_UP      = 0x0BF
MSG_MOVE_START_PITCH_DOWN    = 0x0C0
MSG_MOVE_STOP_PITCH          = 0x0C1
MSG_MOVE_SET_RUN_MODE        = 0x0C2
MSG_MOVE_SET_WALK_MODE       = 0x0C3
MSG_MOVE_TELEPORT            = 0x0C5
MSG_MOVE_FALL_LAND           = 0x0C9
MSG_MOVE_START_SWIM          = 0x0CA
MSG_MOVE_STOP_SWIM           = 0x0CB
MSG_MOVE_SET_FACING          = 0x0DA
MSG_MOVE_SET_PITCH           = 0x0DB
MSG_MOVE_WORLDPORT_ACK       = 0x0DC
MSG_MOVE_ROOT                = 0x0EC
MSG_MOVE_UNROOT              = 0x0ED
MSG_MOVE_HEARTBEAT           = 0x0EE
MSG_MOVE_KNOCK_BACK          = 0x0F1
MSG_MOVE_HOVER               = 0x0F7
MSG_MOVE_TIME_SKIPPED        = 0x319

# Misc client opcodes
CMSG_STANDSTATECHANGE        = 0x101
CMSG_AREATRIGGER             = 0x0B4
CMSG_SET_SELECTION           = 0x13D
CMSG_QUESTGIVER_STATUS_QUERY = 0x182
SMSG_QUESTGIVER_STATUS       = 0x183
CMSG_ZONEUPDATE              = 0x1F4
CMSG_SET_ACTIVE_MOVER        = 0x26A
SMSG_TIME_SYNC_REQ           = 0x390
CMSG_TIME_SYNC_RESP          = 0x391
CMSG_JOIN_CHANNEL            = 0x097
CMSG_LEAVE_CHANNEL           = 0x098

# Move speed changes
SMSG_FORCE_RUN_SPEED_CHANGE  = 0x0E2
SMSG_FORCE_SWIM_SPEED_CHANGE = 0x0E6

# Hover
SMSG_MOVE_SET_HOVER          = 0x0F4
SMSG_MOVE_UNSET_HOVER        = 0x0F5

# Misc
SMSG_WARDEN_DATA             = 0x4C1
